### ISSUE TITLE
作者您好，请问噪声的添加和去除是对潜在特征吗，还是对原始图像；我看代码是对vae.encoder(x)提取的特征，不过论文描述好像是对图像，请问这是为了方便描述吗，还是我的理解有误差，非常感谢！！！

### ISSUE THREAD

**Issue by ZHE-SAPI** [hyao1/GLAD#12]
作者您好，请问噪声的添加和去除是对潜在特征吗，还是对原始图像；我看代码是对vae.encoder(x)提取的特征，不过论文描述好像是对图像，请问这是为了方便描述吗，还是我的理解有误差，非常感谢！！！

**Comment by hyao1** [comment]
是在隐特征上添加，图里的只是为了方便理解，我们有多个不同的隐特征，用图像表述更好区分一些。

**Comment by ZHE-SAPI** [comment]
谢谢
