### ISSUE TITLE
Trained Model Issues

### ISSUE THREAD

**Issue by liaoyusy** [hyao1/GLAD#4]
Hello, I would like to ask for your help. The model you provided is named "pytorch_model.bin", but after training, I got several files as shown in the picture. Which one should I use?
![1720493497997](https://github.com/hyao1/GLAD/assets/16462778/db3d39c9-a07d-420d-936d-53bd17c6231d)

**Comment by hyao1** [comment]
use model.safetensors. It may be caused by different version of diffusers or accelerate package.
