### ISSUE TITLE
作者您好，关于运行bash test.sh on MVTec-AD 的指标问题

### ISSUE THREAD

**Issue by ZHE-SAPI** [hyao1/GLAD#9]
Thank you for your excellent work. 

When I tested the model you shared on OneDrive using the MVTec-AD dataset and ran the bash test_multi.sh, I obtained results of mean: [97.61266667 99.144 96.472 97.29266667 60.59066667 61.024 93.16533333], which are similar to the results reported in Table S7 of the paper. However, when I ran bash test.sh, the results were [98.744 99.41133333 97.52933333 98.52733333 69.76133333 67.39933333 94.88066667], which are lower than the results reported in Table 5 of the paper. Could this be due to random factors, or is this kind of variation normal?

many thanks!

**Comment by ZHE-SAPI** [comment]
If there are any important points I should pay attention to, could you please point it out, thanks

**Comment by ZHE-SAPI** [comment]
bash test.sh on MVTec-AD 各类别指标如下：
test:carpet, checkpoint_step:2000
len(val_dataloader) 59
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:0.9755/0.9936/0.977/0.9856/0.7413/0.7152/0.9339-----

test:grid, checkpoint_step:3000
len(val_dataloader) 39
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:1.0/1.0/1.0/0.9889/0.3607/0.3396/0.959-----

test:leather, checkpoint_step:2500
len(val_dataloader) 62
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:0.9997/0.9999/0.9946/0.9975/0.679/0.6466/0.9865-----

test:tile, checkpoint_step:500
len(val_dataloader) 59
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:1.0/1.0/1.0/0.9866/0.7766/0.7999/0.9702-----

test:wood, checkpoint_step:1000
len(val_dataloader) 40
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:0.9912/0.9973/0.9752/0.9802/0.7839/0.7097/0.9573-----

test:bottle, checkpoint_step:2500
len(val_dataloader) 42
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:0.9984/0.9995/0.992/0.9866/0.8556/0.7924/0.959-----

test:cable, checkpoint_step:1500
len(val_dataloader) 75
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:0.9925/0.9961/0.9783/0.9813/0.706/0.6598/0.9344-----

test:capsule, checkpoint_step:2000
len(val_dataloader) 66
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:0.992/0.9984/0.9774/0.9851/0.5204/0.5335/0.939-----

test:hazelnut, checkpoint_step:3500
len(val_dataloader) 55
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:0.9936/0.9961/0.9859/0.9947/0.8024/0.7322/0.9353-----

test:metal_nut, checkpoint_step:2500
len(val_dataloader) 58
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:1.0/1.0/1.0/0.9884/0.9227/0.8997/0.9685-----

test:pill, checkpoint_step:1500
len(val_dataloader) 84
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:0.9828/0.9969/0.972/0.9783/0.7596/0.7081/0.9732-----

test:screw, checkpoint_step:3000
len(val_dataloader) 80
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:0.9457/0.9821/0.9268/0.9902/0.5289/0.5596/0.9464-----

test:toothbrush, checkpoint_step:500
len(val_dataloader) 21
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:1.0/1.0/1.0/0.9934/0.5872/0.6684/0.9532-----

test:transistor, checkpoint_step:2500
len(val_dataloader) 50
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:0.9662/0.9587/0.8919/0.9635/0.7639/0.7/0.9076-----

test:zipper, checkpoint_step:1000
len(val_dataloader) 76
test-------- I-AUROC/I-AP/I-F1-max/P-AUROC/P-AP/P-F1-max/PRO:0.974/0.9931/0.9583/0.9788/0.676/0.6452/0.9086-----
[98.744      99.41133333 97.52933333 98.52733333 69.76133333 67.39933333
 94.88066667]

**Comment by hyao1** [comment]
I think there is a high probability that this problem is caused by randomness. Because of the randomness of the diffusion generation itself, we cannot guarantee that the result of the generation in different environments is exactly the same. We found the same problem with other diffusion-based algorithms. You can test VisA's results with tesh.sh. The fineturned DINO may alleviate this problem to some extent.

**Comment by ZHE-SAPI** [comment]
> I think there is a high probability that this problem is caused by randomness. Because of the randomness of the diffusion generation itself, we cannot guarantee that the result of the generation in different environments is exactly the same. We found the same problem with other diffusion-based algorithms. You can test VisA's results with tesh.sh. The fineturned DINO may alleviate this problem to some extent.

thank you for your reply!

**Comment by hyao1** [comment]
In fact, the results of the second run should be completely consistent to the first run in same machine and environment because I fixed random seeds. But the random environment is different for different machines, even if the same random seed is used. We tested on the 2080ti and A6000 and got different results.

**Comment by ZHE-SAPI** [comment]
Thank you very much

---- 回复的原邮件 ----
| 发件人 | Hang ***@***.***> |
| 发送日期 | 2024年10月16日 15:42 |
| 收件人 | hyao1/GLAD ***@***.***> |
| 抄送人 | zhang ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [hyao1/GLAD] 作者您好，关于运行bash test.sh on MVTec-AD 的指标问题 (Issue #9) |

In fact, the results of the second run should be completely consistent to the first run in same machine and environment because I fixed random seeds. But the random environment is different for different machines, even if the same random seed is used. We tested on the 2080ti and A6000 and got different results.
